import * as fs from 'fs';
import * as path from 'path';
import type { DatabaseConfig } from './database';
import type { OpenClawConfig } from './openclaw';
import type { AgentConfig } from './agent';

interface EnvParams {
  db: DatabaseConfig;
  openclaw: OpenClawConfig;
  agent: AgentConfig;
}

export async function writeEnvFile(params: EnvParams): Promise<void> {
  const { db, openclaw, agent } = params;

  // Generate a random session secret
  const sessionSecret = `hearth:${randomHex(32)}`;

  const envContent = `# Hearth API configuration — generated by hearth setup
NODE_ENV=production
PORT=3001
APP_NAME=hearth-api
APP_HOST=0.0.0.0

# Auth
AUTH_SESSION_SECRET=${sessionSecret}
AUTH_SESSION_COOKIE_NAME=hearth_session
AUTH_SESSION_COOKIE_SECURE=false
AUTH_SESSION_MAX_AGE_SECONDS=2592000

# OpenClaw
OPENCLAW_BASE_URL=${openclaw.baseUrl}
OPENCLAW_GATEWAY_TOKEN=${openclaw.token}
OPENCLAW_AGENT_TIMEOUT_MS=900000
OPENCLAW_RESPONSES_HTTP_ENABLED=true
OPENCLAW_RESPONSES_HTTP_PATH=/v1/responses

# Database
DATABASE_HOST=${db.host}
DATABASE_PORT=${db.port}
DATABASE_NAME=${db.database}
DATABASE_USER=${db.user}
DATABASE_PASSWORD=${db.password}
DATABASE_SCHEMA=public
DATABASE_SSL=false
DATABASE_AUTO_RUN_MIGRATIONS=false
`;

  // Write to apps/api-nest/.env
  const projectRoot = findProjectRoot();
  const envPath = path.join(projectRoot, 'apps', 'api-nest', '.env');

  if (fs.existsSync(envPath)) {
    const backupPath = envPath + '.backup';
    fs.copyFileSync(envPath, backupPath);
    console.log(`  → Backed up existing .env to .env.backup`);
  }

  fs.writeFileSync(envPath, envContent);
  console.log(`  ✓ Wrote ${envPath}`);

  // Write hearth.json for agent config
  const hearthJsonDir = path.join(require('os').homedir(), '.openclaw');
  const hearthJsonPath = path.join(hearthJsonDir, 'hearth.json');

  if (!fs.existsSync(hearthJsonDir)) {
    fs.mkdirSync(hearthJsonDir, { recursive: true });
  }

  const hearthConfig: Record<string, any> = {};
  try {
    if (fs.existsSync(hearthJsonPath)) {
      Object.assign(hearthConfig, JSON.parse(fs.readFileSync(hearthJsonPath, 'utf-8')));
    }
  } catch {
    // ignore
  }

  hearthConfig.agentId = agent.agentId;
  hearthConfig.agentDisplayName = agent.displayName;

  fs.writeFileSync(hearthJsonPath, JSON.stringify(hearthConfig, null, 2));
  console.log(`  ✓ Wrote ${hearthJsonPath}`);
}

function findProjectRoot(): string {
  let dir = process.cwd();
  for (let i = 0; i < 10; i++) {
    if (fs.existsSync(path.join(dir, 'apps', 'api-nest'))) return dir;
    if (fs.existsSync(path.join(dir, 'packages', 'hearth-cli'))) return dir;
    dir = path.dirname(dir);
  }
  return process.cwd();
}

function randomHex(bytes: number): string {
  const { randomBytes } = require('crypto');
  return randomBytes(bytes).toString('hex');
}
